### ISSUE TITLE
[Fullstack] Test log creation

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#100]
### Description
* We need to verify that users can create logs properly
* There won't be a PR for this ticket. Instead, leave a comment with the cases you tested and any bugs you encountered

### Acceptance Criteria
- [x] Users can add videos to logs
- [x] Users can view their own logs
- [x] Users with 800 hours can submit complex tasks
- [x] These are just examples of tests, make sure to try more cases

### Other Notes
* Try a variety of inputs and edge cases
* Don't upload a ton of videos

**Comment by jaipise** [comment]
### Tests
- entered null data into input fields
- tested whether users with >800 hrs are able to submit the complex tasks (do the complex tasks show up in the options)
- tried uploading images (instead of videos)
- tried uploading text files / pdf (instead of videos)
- added very large numbers for the training hours for the log - shouldthere be a max number of hours that can be added?

### Failed Tests
- When I enter a future date (like 2025) for the date of the log, no error is thrown, even though that is an invalid date
- When I enter a date that is negative, an internal server error is thrown, but maybe the user should see a message telling them what exactly the problem is?
- negative training hours are accepted in the form, even though they shouldn't be (inputting negative hours decreases the total training hours)
- a month and date of 0 are accepted as valid inputs even though they shouldn't be
